name = "VAN UNIVERSAL MOTORS"
description = "Оффициальный производитель коммерческой техники FAW в Республике Узбекистан"
keywords = "VAN UNIVERSAL MOTORS, Оффициальный производитель, коммерческая техника, FAW, Республика Узбекистан"
image = "1vum.webp"
theme = "light"
primary_color = "#003b2c"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://biloliddinabdujalilov.github.io/faw.uz/"

[[sections]]
title = "+998 90 961 50 32"
description = "Менеджер по продажам B2B и B2G"
direction = "column"
item_style = "outline"
primary_color = "#003b2c"
[[sections.items]]
embed_url = "https://youtu.be/tzYdqMRJntk?si=2lzv-oR0s3TSyMeS"
[[sections.items]]
title = "WhatsApp"
description = "Менеджер по продажам B2B и B2G"
url = "https://wa.me/998909615032"
[[sections.items]]
title = "Сайт"
description = "Официальный сайт FAW TRUCKS В Узбекистане"
url = "https://faw.uz/"
[[sections.items]]
title = "Telegram"
description = "Официальный Telegram канал FAW TRUCKS В Узбекистане"
url = "https://t.me/vum_faw_uzbekistan"
[[sections.items]]



[[sections]]
title = "Ссылки"
description = "Социальные сети"
direction = "row"
item_style = "filled"
color = "#003b2c"
primary_color = "#003b2c"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/vum_faw_uzbekistan"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube/ffffff"
title = "YouTube"
url = "https://www.youtube.com/@faw_uzbekistan/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/google/ffffff"
title = "Сайт"
url = "https://faw.uz/"
[[sections.items]]
title = "Facebook"
icon = "https://cdn.simpleicons.org/facebook/ffffff"
url = "https://www.facebook.com/fawuzbekistan"

